
if (isClass (configFile >> "CfgPatches" >> "sab_flyinglegends")) then {
    (["attributesVehicles"] call _fnc_getFromTemplate) append [
        ["sab_fl_a6m", ["cost", 75]],
        ["sab_fl_a6m2n", ["cost", 75]],
        ["sab_fl_bf109c", ["cost", 75]],
        ["sab_fl_bf109e", ["cost", 75]],
        ["sab_fl_bf109f", ["cost", 75]],
        ["sab_fl_bf109g", ["cost", 75]],
        ["sab_fl_bf109k", ["cost", 75]],
        ["sab_fl_fw190a", ["cost", 75]],
        ["sab_fl_fw190d", ["cost", 75]],
        ["sab_fl_g50", ["cost", 75]],
        ["sab_fl_ju86", ["cost", 75]],
        ["sab_fl_ju88a", ["cost", 75]],
        ["sab_fl_ju88c", ["cost", 75]],
        ["sab_fl_ju88g", ["cost", 75]],
        ["sab_fl_yak3", ["cost", 75]],
        ["sab_fl_dh98", ["cost", 75]],
        ["sab_fl_f4f", ["cost", 75]],
        ["sab_fl_f4u", ["cost", 75]],
        ["sab_fl_hurricane", ["cost", 75]],
        ["sab_fl_hurricane_trop", ["cost", 75]],
        ["sab_fl_hurricane_2", ["cost", 75]],
        ["sab_fl_p51b", ["cost", 75]],
        ["sab_fl_p51d", ["cost", 75]],
        ["sab_fl_sbd", ["cost", 75]],
        ["sab_fl_spitfire_mk1", ["cost", 75]],
        ["sab_fl_spitfire_mk5", ["cost", 75]],
        ["sab_fl_spitfire_mkxiv", ["cost", 75]],
        ["sab_fl_tempest", ["cost", 75]],
        ["sab_fl_he162", ["cost", 125]]
    ];
};
if (isClass (configFile >> "CfgPatches" >> "sab_sw_tbf")) then {
    (["attributesVehicles"] call _fnc_getFromTemplate) append [
        ["sab_sw_a26", ["cost", 125]],
        ["sab_sw_b17f", ["cost", 125]],
        ["sab_sw_b17", ["cost", 125]],
        ["sab_sw_b25", ["cost", 75]],
        ["sab_sw_halifax", ["cost", 125]],
        ["sab_sw_p38", ["cost", 75]],
        ["sab_sw_p40", ["cost", 75]],
        ["sab_sw_p61", ["cost", 75]],
        ["sab_sw_tbf", ["cost", 75]],
        ["sab_sw_i16_2", ["cost", 75]],
        ["sab_sw_i16", ["cost", 75]],
        ["sab_sw_il2", ["cost", 75]],
        ["sab_sw_il2_2", ["cost", 75]],
        ["sab_sw_ar234", ["cost", 125]],
        ["sab_sw_b5n", ["cost", 50]],
        ["sab_sw_bf110", ["cost", 75]],
        ["sab_sw_bf110_2", ["cost", 75]],
        ["sab_sw_d3a", ["cost", 75]],
        ["sab_sw_do335", ["cost", 75]],
        ["sab_sw_g55", ["cost", 75]],
        ["sab_sw_he177", ["cost", 125]],
        ["sab_sw_he111", ["cost", 125]],
        ["sab_sw_ju87_2", ["cost", 75]],
        ["sab_sw_ju87_3", ["cost", 75]],
        ["sab_sw_ju87", ["cost", 75]],
        ["sab_sw_me262", ["cost", 125]]
    ];
};